# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'GUIIwWnBz.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setTabShape(QTabWidget.Rounded)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(80, 390, 141, 17))
        self.checkBox_2 = QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(80, 350, 131, 17))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 290, 281, 51))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(True)
        self.label.setFocusPolicy(Qt.NoFocus)
        self.label.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setTextFormat(Qt.MarkdownText)
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setMargin(0)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(90, 130, 561, 31))
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(Qt.NoFocus)
        self.label_2.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_2.setLayoutDirection(Qt.LeftToRight)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setMargin(0)
        self.checkBox_3 = QCheckBox(self.centralwidget)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(80, 470, 251, 17))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(330, 290, 20, 211))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.checkBox_4 = QCheckBox(self.centralwidget)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(80, 430, 251, 21))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(340, 290, 281, 51))
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(True)
        self.label_3.setFocusPolicy(Qt.NoFocus)
        self.label_3.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_3.setLayoutDirection(Qt.LeftToRight)
        self.label_3.setTextFormat(Qt.MarkdownText)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setMargin(0)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(400, 490, 241, 51))
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMouseTracking(True)
        self.label_4.setFocusPolicy(Qt.NoFocus)
        self.label_4.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_4.setLayoutDirection(Qt.LeftToRight)
        self.label_4.setTextFormat(Qt.MarkdownText)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setMargin(0)
        self.spinBox = QSpinBox(self.centralwidget)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(460, 350, 41, 22))
        self.spinBox.setMinimum(2)
        self.spinBox.setMaximum(9999)
        self.spinBox.setSingleStep(2)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(450, 590, 131, 61))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 660, 1021, 41))
        self.label_5.setTextFormat(Qt.AutoText)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 20, 1031, 81))
        font1 = QFont()
        font1.setPointSize(36)
        font1.setBold(True)
        font1.setWeight(75)
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(410, 720, 221, 16))
        self.treeView = QTreeView(self.centralwidget)
        self.treeView.setObjectName(u"treeView")
        self.treeView.setGeometry(QRect(90, 160, 561, 91))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(610, 290, 20, 211))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(690, 160, 211, 91))
        font2 = QFont()
        font2.setBold(True)
        font2.setWeight(75)
        font2.setKerning(True)
        self.groupBox.setFont(font2)
        self.groupBox.setLayoutDirection(Qt.RightToLeft)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setAlignment(Qt.AlignCenter)
        self.radioButton = QRadioButton(self.groupBox)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(50, 20, 51, 20))
        self.radioButton.setLayoutDirection(Qt.RightToLeft)
        self.radioButton_2 = QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(50, 40, 51, 20))
        self.radioButton_3 = QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(50, 60, 51, 20))
        self.radioButton_4 = QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(110, 20, 51, 20))
        self.radioButton_5 = QRadioButton(self.groupBox)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(110, 40, 51, 20))
        self.radioButton_5.setAutoRepeatDelay(0)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(60, 330, 901, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(50, 290, 20, 211))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(950, 290, 20, 211))
        self.line_5.setFrameShape(QFrame.VLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(620, 290, 341, 51))
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setFont(font)
        self.label_8.setMouseTracking(True)
        self.label_8.setFocusPolicy(Qt.NoFocus)
        self.label_8.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_8.setLayoutDirection(Qt.LeftToRight)
        self.label_8.setTextFormat(Qt.MarkdownText)
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_8.setWordWrap(True)
        self.label_8.setMargin(0)
        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(60, 280, 281, 20))
        self.line_6.setFrameShape(QFrame.HLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.line_7 = QFrame(self.centralwidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(60, 490, 901, 20))
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)
        self.spinBox_2 = QSpinBox(self.centralwidget)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(460, 390, 42, 22))
        self.spinBox_2.setMinimum(2)
        self.spinBox_2.setMaximum(9999)
        self.spinBox_2.setSingleStep(2)
        self.spinBox_2.setValue(2)
        self.spinBox_3 = QSpinBox(self.centralwidget)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(460, 430, 42, 22))
        self.spinBox_3.setMinimum(2)
        self.spinBox_3.setMaximum(9999)
        self.spinBox_3.setSingleStep(2)
        self.spinBox_4 = QSpinBox(self.centralwidget)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(350, 470, 42, 22))
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(9999)
        self.spinBox_4.setValue(1)
        self.line_8 = QFrame(self.centralwidget)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(60, 450, 901, 20))
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.line_9 = QFrame(self.centralwidget)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(60, 410, 901, 20))
        self.line_9.setFrameShape(QFrame.HLine)
        self.line_9.setFrameShadow(QFrame.Sunken)
        self.line_10 = QFrame(self.centralwidget)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(60, 370, 901, 20))
        self.line_10.setFrameShape(QFrame.HLine)
        self.line_10.setFrameShadow(QFrame.Sunken)
        self.line_11 = QFrame(self.centralwidget)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(340, 280, 281, 20))
        self.line_11.setFrameShape(QFrame.HLine)
        self.line_11.setFrameShadow(QFrame.Sunken)
        self.line_12 = QFrame(self.centralwidget)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(620, 280, 341, 20))
        self.line_12.setFrameShape(QFrame.HLine)
        self.line_12.setFrameShadow(QFrame.Sunken)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(620, 340, 111, 41))
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMouseTracking(True)
        self.label_9.setFocusPolicy(Qt.NoFocus)
        self.label_9.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_9.setLayoutDirection(Qt.LeftToRight)
        self.label_9.setTextFormat(Qt.MarkdownText)
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setMargin(0)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(800, 340, 111, 41))
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMouseTracking(True)
        self.label_10.setFocusPolicy(Qt.NoFocus)
        self.label_10.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_10.setLayoutDirection(Qt.LeftToRight)
        self.label_10.setTextFormat(Qt.MarkdownText)
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setMargin(0)
        self.spinBox_5 = QSpinBox(self.centralwidget)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(730, 350, 41, 22))
        self.spinBox_5.setMaximum(100)
        self.spinBox_6 = QSpinBox(self.centralwidget)
        self.spinBox_6.setObjectName(u"spinBox_6")
        self.spinBox_6.setGeometry(QRect(910, 350, 41, 22))
        self.spinBox_6.setMaximum(100)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(800, 380, 111, 41))
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMouseTracking(True)
        self.label_11.setFocusPolicy(Qt.NoFocus)
        self.label_11.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_11.setLayoutDirection(Qt.LeftToRight)
        self.label_11.setTextFormat(Qt.MarkdownText)
        self.label_11.setScaledContents(True)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_11.setWordWrap(True)
        self.label_11.setMargin(0)
        self.spinBox_7 = QSpinBox(self.centralwidget)
        self.spinBox_7.setObjectName(u"spinBox_7")
        self.spinBox_7.setGeometry(QRect(910, 390, 41, 22))
        self.spinBox_7.setMaximum(100)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(620, 380, 111, 41))
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMouseTracking(True)
        self.label_12.setFocusPolicy(Qt.NoFocus)
        self.label_12.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_12.setLayoutDirection(Qt.LeftToRight)
        self.label_12.setTextFormat(Qt.MarkdownText)
        self.label_12.setScaledContents(True)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_12.setMargin(0)
        self.spinBox_8 = QSpinBox(self.centralwidget)
        self.spinBox_8.setObjectName(u"spinBox_8")
        self.spinBox_8.setGeometry(QRect(730, 390, 41, 22))
        self.spinBox_8.setMaximum(100)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(800, 420, 111, 41))
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMouseTracking(True)
        self.label_13.setFocusPolicy(Qt.NoFocus)
        self.label_13.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_13.setLayoutDirection(Qt.LeftToRight)
        self.label_13.setTextFormat(Qt.MarkdownText)
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setMargin(0)
        self.spinBox_9 = QSpinBox(self.centralwidget)
        self.spinBox_9.setObjectName(u"spinBox_9")
        self.spinBox_9.setGeometry(QRect(910, 430, 41, 22))
        self.spinBox_9.setMaximum(100)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(620, 420, 111, 41))
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMouseTracking(True)
        self.label_14.setFocusPolicy(Qt.NoFocus)
        self.label_14.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_14.setLayoutDirection(Qt.LeftToRight)
        self.label_14.setTextFormat(Qt.MarkdownText)
        self.label_14.setScaledContents(True)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setMargin(0)
        self.spinBox_10 = QSpinBox(self.centralwidget)
        self.spinBox_10.setObjectName(u"spinBox_10")
        self.spinBox_10.setGeometry(QRect(730, 430, 41, 22))
        self.spinBox_10.setMaximum(100)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(650, 460, 211, 41))
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMouseTracking(True)
        self.label_15.setFocusPolicy(Qt.NoFocus)
        self.label_15.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_15.setLayoutDirection(Qt.LeftToRight)
        self.label_15.setTextFormat(Qt.MarkdownText)
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_15.setWordWrap(True)
        self.label_15.setMargin(0)
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(390, 460, 231, 41))
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        font3 = QFont()
        font3.setPointSize(7)
        self.label_16.setFont(font3)
        self.label_16.setMouseTracking(True)
        self.label_16.setFocusPolicy(Qt.NoFocus)
        self.label_16.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_16.setLayoutDirection(Qt.LeftToRight)
        self.label_16.setTextFormat(Qt.MarkdownText)
        self.label_16.setScaledContents(True)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_16.setWordWrap(True)
        self.label_16.setMargin(0)
        self.doubleSpinBox = QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(860, 470, 62, 22))
        self.doubleSpinBox.setMaximum(1000.000000000000000)
        self.label_17 = QLabel(self.centralwidget)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(-4, 700, 1031, 20))
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_17.setTextInteractionFlags(Qt.LinksAccessibleByMouse|Qt.TextSelectableByMouse)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1024, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"An\u00e1lise de incerteza do HEC-RAS", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Coeficiente de Manning", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"Vaz\u00f5es de entrada", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Selecione os par\u00e2metros que deseja analisar via Monte Carlo", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Selecione o arquivo .prj do seu projeto do HEC-RAS:", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"Condi\u00e7\u00e3o de contorno a jusante \"Known W.S.\"", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"Condi\u00e7\u00e3o de contorno a jusante \"Normal depth\"", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Selecione o n\u00famero de simula\u00e7\u00f5es por an\u00e1lise que deseja realizar", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"LEMBRE-SE: a quantidade de itera\u00e7\u00f5es ir\u00e1 afetar o tempo de processamento do programa.", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Executar a an\u00e1lise!", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"O HEC-RAS DEVE  ESTAR FECHADO!", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"An\u00e1lise de incerteza do HEC-RAS", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Desenvolvido por Giovanni Madalozzo Oliveira", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Selecione a vers\u00e3o do seu HEC-RAS", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"5.0.1", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"5.0.3", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"5.0.5", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"5.0.6", None))
        self.radioButton_5.setText(QCoreApplication.translate("MainWindow", u"5.0.7", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Perturba\u00e7\u00e3o no par\u00e2metro por rodada", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Limite m\u00ednimo (-%)", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Limite m\u00e1ximo (%)", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Limite m\u00e1ximo (%)", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Limite m\u00ednimo (-%)", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Limite m\u00e1ximo (%)", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Limite m\u00ednimo (-%)", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Varia\u00e7\u00e3o do n\u00edvel  por rodada (m)", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"OBS: ser\u00e1 realizado esse n\u00fam. de simula\u00e7\u00f5es acima e abaixo do valor atual. Ex: 1 =valor atual-varia\u00e7\u00e3o, valor atual, valor atual+varia\u00e7\u00e3o", None))
        self.label_17.setText("")
    # retranslateUi

