# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Tentativa1RqbukZ.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.checkBox = QCheckBox(self.centralwidget)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(170, 450, 141, 17))
        self.checkBox_2 = QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(170, 470, 131, 17))
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(170, 400, 251, 51))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMouseTracking(True)
        self.label.setFocusPolicy(Qt.NoFocus)
        self.label.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setTextFormat(Qt.MarkdownText)
        self.label.setScaledContents(True)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setMargin(0)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(120, 150, 801, 31))
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setFocusPolicy(Qt.NoFocus)
        self.label_2.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_2.setLayoutDirection(Qt.LeftToRight)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setMargin(0)
        self.checkBox_3 = QCheckBox(self.centralwidget)
        self.checkBox_3.setObjectName(u"checkBox_3")
        self.checkBox_3.setGeometry(QRect(170, 490, 251, 17))
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(410, 400, 20, 151))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.checkBox_4 = QCheckBox(self.centralwidget)
        self.checkBox_4.setObjectName(u"checkBox_4")
        self.checkBox_4.setGeometry(QRect(170, 510, 251, 17))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(420, 400, 251, 51))
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMouseTracking(True)
        self.label_3.setFocusPolicy(Qt.NoFocus)
        self.label_3.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_3.setLayoutDirection(Qt.LeftToRight)
        self.label_3.setTextFormat(Qt.MarkdownText)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setMargin(0)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(430, 480, 241, 51))
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMouseTracking(True)
        self.label_4.setFocusPolicy(Qt.NoFocus)
        self.label_4.setContextMenuPolicy(Qt.DefaultContextMenu)
        self.label_4.setLayoutDirection(Qt.LeftToRight)
        self.label_4.setTextFormat(Qt.MarkdownText)
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setMargin(0)
        self.spinBox = QSpinBox(self.centralwidget)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(530, 450, 42, 22))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(450, 600, 131, 61))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(0, 665, 1021, 61))
        self.label_5.setTextFormat(Qt.AutoText)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(140, 10, 761, 81))
        font = QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(800, 710, 221, 16))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(480, 570, 75, 23))
        self.treeView = QTreeView(self.centralwidget)
        self.treeView.setObjectName(u"treeView")
        self.treeView.setGeometry(QRect(120, 180, 801, 192))
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(660, 400, 20, 151))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(670, 410, 201, 131))
        self.radioButton = QRadioButton(self.groupBox)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(10, 20, 82, 17))
        self.radioButton_2 = QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(10, 40, 82, 17))
        self.radioButton_3 = QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(10, 60, 82, 17))
        self.radioButton_4 = QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(10, 80, 82, 17))
        self.radioButton_5 = QRadioButton(self.groupBox)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(10, 100, 82, 17))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1024, 21))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Coeficiente de Manning", None))
        self.checkBox_2.setText(QCoreApplication.translate("MainWindow", u"Vaz\u00f5es de entrada", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Selecione os par\u00e2metros que deseja analisar via Monte Carlo:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Selecione o arquivo .prj do seu projeto do HEC-RAS:", None))
        self.checkBox_3.setText(QCoreApplication.translate("MainWindow", u"Condi\u00e7\u00e3o de contorno a jusante \"Known W.S.\"", None))
        self.checkBox_4.setText(QCoreApplication.translate("MainWindow", u"Condi\u00e7\u00e3o de contorno a jusante \"Normal depth\"", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Selecione o n\u00famero de simula\u00e7\u00f5es por an\u00e1lise que deseja realizar:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"LEMBRE-SE: essa op\u00e7\u00e3o ir\u00e1 afetar o tempo de processamento do programa.", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Executar a an\u00e1lise!", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"O HEC-RAS DEVE  ESTAR FECHADO!", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"T\u00edtulo", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Desenvolvido por Giovanni Madalozzo Oliveira", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Ajuda", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Selecione a vers\u00e3o do seu HEC-RAS:", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"5.0.1", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"5.0.3", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"5.0.5", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"5.0.6", None))
        self.radioButton_5.setText(QCoreApplication.translate("MainWindow", u"5.0.7", None))
    # retranslateUi

